/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 30.0
    image_width: 1280
    image_height: 720
    pixel_format: "mjpeg2rgb"
    io_method: "mmap"
    camera_name: "c920"
    frame_id: "camera"
